config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get 'home/about'=>'homes#about'

  resources :users, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  add_flash_types :success, :info, :warning, :danger


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user[:id])
    @book_new = Book.new


  end

  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])

  unless @book.user_id == current_user.id
    redirect_to books_path
  end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

 private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
  
  def about

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end



  def edit
    @user = User.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to user_path(user.id)
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :option)
  end

  def book_params
    params.require(:book).permit(:title, :body, :option)
  end

  def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>error occurred
          <ul>
            <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
      <%= form_with model: @book,method: :patch do |f| %>
      <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, autofocus: true, id:"book_title", class:"form-control book_title"%>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Update Book', class:"btn btn-success" %>
  </div>
<% end %>
  		<%= link_to book_path(@book.id) do %>
  		Show
  		<% end %>
        |
  		<a class="back" href="/books">Back</a>
  </div>
</div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

  <% if @book.errors.any? %>
      <%= @book.errors.count %>error occurred
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= form_with model: @user, url:edit_user_path(@user.id), method: :patch do |f| %>
  <table class="table">
    <tbody>
      <tr>
        <%= image_tag @user.get_profile_image(100,100) %>
      </tr>
      <tr>
        <th>name</th>
        <th>
          <%= @user.name %>
        </th>
      </tr>
      <tr>
        <th>introduction</th>
        <th>
          <%= @user.introduction %>
        </th>
      </tr>
      <% end %>
    </tbody>
  </table>


    <div class="row">
      <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </div>


    <h2 class="mt-3">New book</h2>

    <%= form_with model: @book do |f| %>
      <h5>Title</h5>
      <%= f.text_field :title %>

      <h5>Option</h5>
      <%= f.text_area :body %>

      <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
      </div>
    <% end %>
    </div>


    <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>title</th>
          <th>option</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(50,50) %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title,book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>


        </div>
        </div>
        </div>

app/views/books/show.html.erb
<p id="notice"></p>


<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
          <h2>User info</h2>
            <table class="table">
              <tbody>
                <tr>
                  <%= image_tag @user.get_profile_image(100,100) %>
                </tr>
                <tr>
                  <th>name</th>
                  <th>
                  <%= @user.name %>
                  </th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th>
                  <%= @user.introduction %>
                  </th>
                </tr>
              </tbody>
            </table>


    <div class="row">
      <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </div>


    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book_new do |f| %>
      <h5>Title</h5>
      <%= f.text_field :title %>

      <h5>Option</h5>
      <%= f.text_area :body %>

      <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
      </div>
    <% end %>
    </div>


    <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">
      <tbody>
          <tr>
            <td></td>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= image_tag @user.get_profile_image(50,50) %>
              <% end %>
              <%= link_to user_path(@user.id) do %></br>
              <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <% if @book.user == current_user %>
            <td>
                <%= link_to edit_book_path(@book), class:"btn btn-sm btn-success" do %>Edit
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book), class:"btn btn-sm btn-danger", method: :delete %>
            </td>
            <% end %>
          </tr>
        <% end %>


      </tbody>
    </table>


        </div>
        </div>
        </div>

app/views/homes/about.html.erb
<p class="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i> Bookers</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to  <i class="fas fa-book"></i> Bookers!!</h1>

<p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>
            <p>in <i class="fas fa-book"></i>Bookers</p>

            <p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>
        </div>
    </div>
</div>

    <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">


      <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
          <i class="fas fa-home"></i> Home
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to root_path, class: 'nav-link text-light' do %>
          <i class="fas fa-home"></i> Home
          <% end %>
        </li>
      <% end %>




      <% if user_signed_in? %>
      <li>
        <%= link_to users_path, class: 'nav-link text-light' do %>
        <i class="fas fa-users"></i> Users
        <% end %>
      </li>
      <li>
        <%= link_to books_path, class: 'nav-link text-light' do %>
        <i class="fas fa-book-open"></i> Books
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, class: 'nav-link text-light', method: :delete do %>
        <i class="fas fa-sign-out-alt"></i> Log out
        <% end %>
      </li>
        <% else %>
      <li>
        <%= link_to home_about_path, class: 'nav-link text-light' do %>
        <i class="fas fa-link"></i> About
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i> Sign up
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i> Log in
        <% end %>
      </li>
    <% end %>
    </ul>
    </div>
    </div>
    </nav>
    </header>
    <%= flash[:notice] %>
    <%= yield %>






    <footer>
    <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
    </footer>

  </body>

</html>

app/views/users/edit.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
          <% if @user.errors.any? %>
            <%= @user.errors.count %>error occurred
            <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
    <% end %>



    <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, autofocus: true, id:"user_name", placeholder:"名前", class:"form-control name"%>
      </div>
     <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class:"form-control-file user_image" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class:"form-control introduction" %>
       </div>
      <div class="form-group">
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      </div>
<% end %>
</div>
</div>

      </div>

app/views/users/index.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
          <h2>User info</h2>
          <%= form_with model: @user, url:edit_user_path(@user.id), method: :patch do |f| %>
            <table class="table">
              <tbody>
                <tr>
                  <%= image_tag @user.get_profile_image(100,100) %>
                </tr>
                <tr>
                  <th>name</th>
                  <th>
                  <%= @user.name %>
                  </th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th>
                  <%= @user.introduction %>
                  </th>
                </tr>
                <% end %>
              </tbody>
            </table>


    <div class="row">
      <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </div>


    <h2 class="mt-3">New book</h2>
  
       <%= form_with model: @book do |f| %>
        <h5>Title</h5>
        <%= f.text_field :title %>

        <h5>Option</h5>
        <%= f.text_area :body %>

              <div class="form-group">
              <%= f.submit 'Create Book', class:"btn btn-success" %>
              </div>
              <% end %>
    </div>


    <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>

          <tr>
            <td>
              <%= image_tag user.get_profile_image(50,50) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to user_path(user.id) do %>
  		        Show
  		        <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>


        </div>
        </div>
        </div>

app/views/users/show.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
          <h2>User info</h2>
    <table class="table">
    <tbody>
      <tr>
        <%= image_tag @user.get_profile_image(100,100) %>
      </tr>
      <tr>
        <th>name</th>
        <th>
          <%= @user.name %>
        </th>
      </tr>
      <tr>
        <th>introduction</th>
        <th>
          <%= @user.introduction %>
        </th>
      </tr>

    </tbody>
    </table>


    <div class="row">
      <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </div>


    <h2 class="mt-3">New book</h2>

    <%= form_with model: @book do |f| %>
      <h5>Title</h5>
      <%= f.text_field :title %>

      <h5>Option</h5>
      <%= f.text_area :body %>

      <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
      </div>
    <% end %>
    </div>


    <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table">
      <thead>
        <tr>
          <th>title</th>
          <th>option</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(50,50) %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title,book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>


        </div>
        </div>
        </div>